import turtle
t = turtle.Pen()
t.speed(0)
wn=turtle.Screen()
wn.bgcolor("black")
t.shape("turtle")
t.color("white")
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
